### ISSUE TITLE
Topic [idea] suggestion for the near future episodes 

### ISSUE THREAD

**Issue by nrndev** [level-up-hour/episodes#14]
📓  **Topic of suggestion ** : 
                   ⭐ What is a api gateway ? 🤔 
                   ⭐ how it'll help in the cloud native world 🚨  ? 
                   ⭐ what are it's implications when combined with service meshes ? Advantages and disadvantages of it ?
                   ⭐ Maybe a simple real life working example in the show and implementation. 💻 

📚 **Reason** : 
 The world 🌏 🌍 🌎  of kubernetes and openshift is huge and there are lots of plugins and entities are added as layers by layers. 

In the show we do take a layers apart and discuss it and build up on it. 🥏 
Yet there isn't much diversity  in the content flow as it going in a narrow pipeline of dev to prod devops flows. 📇 

Would love to see some discussion and knowledge bursts in this topic. ❤️ 🛸 ✌️

**Comment by langdon** [comment]
@narenarjun please ping me on discord to log your Sweet, Sweet Internet Points; Added to the show backlog;
