### ISSUE TITLE
A Question for discussion in the show 

### ISSUE THREAD

**Issue by nrndev** [level-up-hour/episodes#15]
❓  ❓ **Question** : 
                      ⭐ Why UBI images are bigger than alpine images ? 
                      ⭐ What makes them special ? 
                      ⭐ Is it already hardened with necessary *SELinux* configs or we have to tune it to our preferences ?

**Comment by langdon** [comment]
@narenarjun please ping me on discord to log your Sweet, Sweet Internet Points; Added to the show backlog;
